name: Build Binaries

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name auto-news-windows main.py
    
    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: auto-news-windows
        path: dist/auto-news-windows.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name auto-news-linux main.py
    
    - name: Upload Linux binary
      uses: actions/upload-artifact@v3
      with:
        name: auto-news-linux
        path: dist/auto-news-linux